"""
We use this diagnostic script to validate the feature outputs generated by feature_script.py
and evaluate how those features influence the XGBoost model's predictions.
Loads the Parquet feature table generated by the feature pipeline.
Imports FEATURE_NAMES from feature_factory.py.
Verifies that all expected features are present.
Verifies that the feature names and ordering exactly match what the XGBoost model expects.
Scores all clean-2020 samples using the trained model.
Examines how the resulting model scores relate to individual features.
Breaks down scores by vessel type and baseline quality.
Checks whether fallback baselines are associated with unusually high scores.
"""
import sys
from pathlib import Path
import numpy as np
import pandas as pd
import xgboost as xgb
BASE_DIR = Path(__file__).resolve().parent.parent  # repo root
XGB_MODEL = BASE_DIR / "hybrid" / "xgboost_hybrid_final.json"
FEATURES_PATH = BASE_DIR / "hybrid" / "hybrid_features_clean_2020_with_scores.parquet"
sys.path.insert(0, str(BASE_DIR / "mlops"))
from feature_factory import FEATURE_NAMES

# ============================================================
# LOAD DATA
# ============================================================
print("Loading feature table...")
df = pd.read_parquet(FEATURES_PATH)
print(f"Rows: {len(df)}")
print(f"Columns: {len(df.columns)}")

# ============================================================
# CHECK FEATURE SCHEMA
# ============================================================
# Columns that are metadata and NOT model features
METADATA_COLUMNS = {
    "MMSI",
    "label",
    "incident_type",
    "year",
}

# Convert to list/set explicitly
expected_features = list(FEATURE_NAMES)
expected_feature_set = set(expected_features)
actual_columns = set(df.columns)
# Features required by the model but missing from Parquet
missing_features = expected_feature_set - actual_columns
# Extra columns that are not model features or metadata
extra_columns = actual_columns - expected_feature_set - METADATA_COLUMNS
print("\nFeature schema check:")
if missing_features:
    print("ERROR: Missing features:")
    for feature in sorted(missing_features):
        print(f"  - {feature}")

    raise ValueError(
        f"Parquet is missing features the model expects: {missing_features}"
    )

print("✓ All 55 expected features are present.")
if extra_columns:
    print("\nExtra columns in Parquet that will NOT be used:")
    for column in sorted(extra_columns):
        print(f"  - {column}")
else:
    print("✓ No unexpected feature columns found.")


# ============================================================
# LOAD XGBOOST MODEL
# ============================================================
print("\nLoading XGBoost model...")
booster = xgb.Booster()
booster.load_model(str(XGB_MODEL))
print(f"Model expects {len(booster.feature_names)} features.")

# ============================================================
# VERIFY MODEL FEATURE ORDER
# ============================================================
model_features = list(booster.feature_names)
if expected_features != model_features:
    print("\nERROR: Feature order/schema mismatch!")

    print("\nFEATURE_FACTORY order:")
    for i, feature in enumerate(expected_features):
        print(f"{i:02d}: {feature}")

    print("\nXGBOOST MODEL order:")
    for i, feature in enumerate(model_features):
        print(f"{i:02d}: {feature}")

    raise ValueError(
        "FEATURE_NAMES from feature_factory.py do not exactly match "
        "the feature order stored in the XGBoost model."
    )

print("✓ Feature names and order match the XGBoost model.")
print(f"✓ Using exactly {len(expected_features)} features.")


# ============================================================
# CREATE DMatrix
# ============================================================
feature_cols = expected_features
dmat = xgb.DMatrix(
    df[feature_cols],
    feature_names=feature_cols,
)

print("\nScoring clean-2020 windows...")

scores = booster.predict(dmat)
df["model_score"] = scores

corr_cols = [
    "speed_over_ground_knots_std",
    "heading_change_deg_std",
    "acceleration_knots_per_sec_std",
    "dist_from_vessel_centroid_km_mean",
    "vessel_type_code",
    "length_m",
    "width_m",
    "baseline_is_fallback",
    "model_score",
]

print("\n" + "=" * 70)
print("CORRELATION WITH MODEL SCORE")
print("=" * 70)

correlations = (
    df[corr_cols]
    .corr(numeric_only=True)["model_score"]
    .sort_values(ascending=False)
)

print(correlations.to_string())

major_types = [30, 90, 31, 60, 37]

print("\n" + "=" * 70)
print("CORRELATION WITHIN MAJOR VESSEL TYPES")
print("=" * 70)

motion_cols = [
    "speed_over_ground_knots_std",
    "heading_change_deg_std",
    "acceleration_knots_per_sec_std",
    "dist_from_vessel_centroid_km_mean",
]

for vessel_type in major_types:

    subset = df[df["vessel_type_code"] == vessel_type]

    if len(subset) < 10:
        continue

    print(f"\nVessel type {vessel_type}")
    print(f"Windows: {len(subset):,}")
    print(f"Vessels: {subset['MMSI'].nunique():,}")

    correlations_type = (
        subset[motion_cols + ["model_score"]]
        .corr(numeric_only=True)["model_score"]
        .drop("model_score")
        .sort_values(ascending=False)
    )

    print(correlations_type.to_string())

    print(f"Mean score:   {subset['model_score'].mean():.4f}")
    print(f"Median score: {subset['model_score'].median():.4f}")
    print(
        f"90th %:       "
        f"{np.percentile(subset['model_score'], 90):.4f}"
    )

print("\n" + "=" * 60)
print("CLEAN-2020 POPULATION DIAGNOSTICS")
print("=" * 60)

# ------------------------------------------------------------
# 1. Baseline fallback rate
# ------------------------------------------------------------

fallback_rate = df["baseline_is_fallback"].mean()

print("\n1. baseline_is_fallback")
print(f"   Fallback rate: {fallback_rate:.4%}")
print(f"   Real baseline: {(1 - fallback_rate):.4%}")

# Compare score distributions for fallback vs real baselines
print("\n   Score distribution by baseline type:")

fallback_scores = df.loc[
    df["baseline_is_fallback"] == 1,
    "model_score"
]

real_baseline_scores = df.loc[
    df["baseline_is_fallback"] == 0,
    "model_score"
]

if len(fallback_scores) > 0:
    print("\n   FALLBACK BASELINES:")
    print(f"      Windows: {len(fallback_scores):,}")
    print(f"      Mean:    {fallback_scores.mean():.4f}")
    print(f"      Median:  {fallback_scores.median():.4f}")
    print(f"      90th %:  {np.percentile(fallback_scores, 90):.4f}")

if len(real_baseline_scores) > 0:
    print("\n   REAL BASELINES:")
    print(f"      Windows: {len(real_baseline_scores):,}")
    print(f"      Mean:    {real_baseline_scores.mean():.4f}")
    print(f"      Median:  {real_baseline_scores.median():.4f}")
    print(f"      90th %:  {np.percentile(real_baseline_scores, 90):.4f}")


# ------------------------------------------------------------
# 2. Score by vessel type
# ------------------------------------------------------------

print("\n2. SCORE BY VESSEL TYPE")

per_type = (
    df.groupby("vessel_type_code")
      .agg(
          windows=("MMSI", "size"),
          vessels=("MMSI", "nunique"),
          mean_score=("model_score", "mean"),
          median_score=("model_score", "median"),
          p90_score=("model_score", lambda x: np.percentile(x, 90)),
          fallback_rate=("baseline_is_fallback", "mean"),
      )
      .sort_values("mean_score", ascending=False)
)

print(per_type.to_string())


# ------------------------------------------------------------
# 3. Overall score distribution again
# ------------------------------------------------------------

print("\n3. OVERALL SCORE DISTRIBUTION")

print(f"   Mean:              {scores.mean():.4f}")
print(f"   Median:            {np.median(scores):.4f}")
print(f"   90th percentile:   {np.percentile(scores, 90):.4f}")
print(f"   95th percentile:   {np.percentile(scores, 95):.4f}")


# ------------------------------------------------------------
# 4. Check whether fallback correlates with high scores
# ------------------------------------------------------------

print("\n4. HIGH-SCORE WINDOWS")

for threshold in [0.05, 0.10, 0.25, 0.50, 0.75, 0.77, 0.85]:
    subset = df[df["model_score"] >= threshold]

    if len(subset) == 0:
        print(f"   Score >= {threshold:.2f}: 0 windows")
        continue

    high_score_fallback_rate = subset["baseline_is_fallback"].mean()

    print(
        f"   Score >= {threshold:.2f}: "
        f"{len(subset):,} windows "
        f"({len(subset) / len(df):.2%}), "
        f"fallback={high_score_fallback_rate:.2%}"
    )


# ------------------------------------------------------------
# 5. Highest-scoring vessel types
# ------------------------------------------------------------

print("\n5. TOP VESSEL TYPES BY MEAN SCORE")

print(
    per_type[
        [
            "windows",
            "vessels",
            "mean_score",
            "median_score",
            "p90_score",
            "fallback_rate",
        ]
    ].head(10).to_string()
)

print("\n" + "=" * 60)
print("END DIAGNOSTICS")
print("=" * 60)

# ============================================================
# SCORE DISTRIBUTION
# ============================================================

print("\nClean-2020 score distribution:")

print(f"  Mean:              {scores.mean():.4f}")
print(f"  Std:               {scores.std():.4f}")
print(f"  Min:               {scores.min():.4f}")
print(f"  Max:               {scores.max():.4f}")
print(f"  10th percentile:   {np.percentile(scores, 10):.4f}")
print(f"  25th percentile:   {np.percentile(scores, 25):.4f}")
print(f"  50th percentile:   {np.percentile(scores, 50):.4f}")
print(f"  90th percentile:   {np.percentile(scores, 90):.4f}")
print(f"  95th percentile:   {np.percentile(scores, 95):.4f}")


# ============================================================
# EXTRA COLUMN REPORT
# ============================================================

print("\nColumns excluded from model scoring:")

excluded_columns = sorted(
    set(df.columns) - set(feature_cols)
)

for column in excluded_columns:
    print(f"  - {column}")